//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteWithEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster1
    {
        public long ID { get; set; }
        public string EmpName { get; set; }
        public double Salary { get; set; }
        public string Designation { get; set; }
        public string fecha { get; set; }
    }
}
