//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteWithEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public Nullable<double> precio { get; set; }
    }
}
